#!/bin/bash 

GREEN='\033[1;32m'
RED='\033[1;31m'
CYAN='\033[1;36m'
YELLOW='\033[1;33m'

get_os_name_version() {
    echo -e "${GREEN}---------- OS Name and Version ----------\n"
    grep -w "PRETTY_NAME" /etc/os-release | cut -d= -f2 | tr -d '"'
    echo -e "\n${GREEN}-----------------------------------------\n"
}

get_kernel_version() {
    echo -e "${GREEN}---------- Kernel Version ----------\n"
    uname -r
    echo -e "\n${GREEN}------------------------------------\n"
}

get_system_arch() {
    echo -e "${GREEN}---------- System Architecture ----------\n"
    uname -m
    echo -e "\n${GREEN}-----------------------------------------\n"
}

get_installed_packages() {
    echo -e "${GREEN}---------- Installed Packages (Count) ----------\n"
    if command -v dpkg &> /dev/null; then
        echo -e "${CYAN}$(dpkg -l | grep -c '^ii') packages installed (dpkg)"
    elif command -v rpm &> /dev/null; then
        echo -e "${CYAN}$(rpm -qa | wc -l) packages installed (rpm)"
    else
        echo -e "${RED}Package manager not supported for basic count."
    fi
    echo -e "\n${GREEN}------------------------------------------------\n"
}

get_logged_in_users() {
    echo -e "${GREEN}---------- Logged-in Users ----------\n"
    w
    echo -e "\n${GREEN}-------------------------------------\n"
}

get_services_and_processes() {
    echo -e "${GREEN}---------- Running Services and Active Processes ----------\n"
    echo -e "${YELLOW}Active Processes: ${CYAN}$(ps aux | wc -l)"
    if command -v systemctl &> /dev/null; then
        echo -e "${YELLOW}Running Services: ${CYAN}$(systemctl list-units --type=service --state=running | grep -c '\.service')"
    else
        echo -e "${RED}Systemd not found."
    fi
    echo -e "\n${GREEN}-----------------------------------------------------------\n"
}

get_open_ports() {
    echo -e "${GREEN}---------- Open Ports ----------\n"
    ss -tuln
    echo -e "\n${GREEN}--------------------------------\n"
}

os_partial_report() {
    if [[ ! -d reports ]]; then
      mkdir reports
    fi
    report_file=~/reports/partial_software_report.txt
    >"$report_file"
    {
        echo -e "====================================="
        echo "      PARTIAL OS & SOFTWARE REPORT     "
        echo "====================================="
        echo "Hostname: $(hostname)"
        echo "Date: $(date +'%d/%m/%Y %H:%M')"
        echo "1-the os name and version: "
        get_os_name_version
        echo "2-the kernel of the device:"
        get_kernel_version
        echo "3-the system architecture:"
        get_system_arch
        echo "4-the currently logged in users:"
        get_logged_in_users
        echo -e "\nthe report is Generated by: $(whoami)"
    } > "$report_file"
    cat "$report_file"
}

os_full_report() {
    if [[ -d reports ]]; then
      mkdir reports
    fi
    report_file=~/reports/full_software_report.txt
    >"$report_file"
    {
        echo -e "====================================="
        echo "        FULL OS & SOFTWARE REPORT      "
        echo "====================================="
        echo "Hostname: $(hostname)"
        echo "Date: $(date +'%d/%m/%Y %H:%M')"
        echo "1-the os name and version:"
        get_os_name_version
        echo "2-the kernel version:"
        get_kernel_version
        echo "3-the system architecture:"
        get_system_arch
        echo "4-the current logged in useers:"
        get_logged_in_users
        echo "5-the installed packages in the system:"
        get_installed_packages
        echo "6-the services running in the device:"
        get_services_and_processes
        echo "7-the open ports are:"
        get_open_ports
        echo -e "\nGenerated by: $(whoami)"
    } > "$report_file"
    cat "$report_file"
}

software_menu(){
  while true
  do
    echo -e "${CYAN}select the option you want to get:"
    echo -e "${GREEN}[1] information about the os name and version"
    echo -e "${GREEN}[2] information about the kernel version"
    echo -e "${GREEN}[3] information about the system architecture"
    echo -e "${GREEN}[4] information about the installed packages"
    echo -e "${GREEN}[5] information about the logged in users"
    echo -e "${GREEN}[6] information about the services and the porcesses"
    echo -e "${GREEN}[7] information about the opne ports"
    echo -e "${RED}[8] quit"

    read -r -p "$(echo -e "${CYAN}nscs-audit\>")" num

    case $num in 
      1)get_os_name_version ;;
      2)get_kernel_version ;;
      3)get_system_arch ;;
      4)get_installed_packages ;;
      5)get_logged_in_users ;;
      6)get_services_and_processes ;;
      7)get_open_ports ;;
      8)break ;;
      *) echo "please select ne of the options" ;;
    esac
  done
}

software_report(){
  while true 
  do
    echo -e "${GREEN}select the format of the report:"
    echo -e "${CYAN}1)patial report"
    echo -e "${CYAN}2)full report"
    echo -e "${RED}3)quit"

    read -r num

    case $num in 
      1)os_partial_report ;;
      2)os_full_report ;;
      3)break ;;
      *) echo -e "${YELLOW}please select one of the options" ;;
    esac
  done
}
